### ISSUE TITLE
Demo 500 error

### ISSUE THREAD

**Issue by leekool** [martykuentzel/sveltekit-tailwind-ecommerce#9]
the link to the demo in the readme returns a 500 "Internal Error".
![14Jan24-07 53 41](https://github.com/martykuentzel/sveltekit-tailwind-ecommerce/assets/88203649/7d0dc066-a38f-45e8-868f-4038cc27dea7)

**Comment by martykuentzel** [comment]
Yeah thanks for the note. I will fix it in the upcoming weeks and might overhaul the code a bit :)

**Comment by martykuentzel** [comment]
Fixed now
